language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker

before_install:
  - docker build -t solamnia/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true solamnia/docker-react npm run test